export type TimelineItem = {
  id: string
  time: string
  title: string
  kind: 'route' | 'place' | 'food' | 'quest' | 'rest'
  details: string[]
}

export type Riddle = {
  question: string
  hint: string
  options: string[]
  answer: number
  explanation: string
  location?: string
}

export type TripDay = {
  id: string
  date: string
  dateLabel: string
  city: string
  eyebrow: string
  title: string
  subtitle: string
  cover: string
  mapFile?: string
  mapNote?: string
  mapRouteScenes?: string[][]
  mapStartProgress?: number
  achievementId?: string
  achievementTitle?: string
  claimLabel?: string
  fact: string
  riddle: Riddle
  timeline: TimelineItem[]
}

export type Achievement = {
  id: string
  title: string
  description: string
  type: 'story' | 'secret' | 'meta'
  unlockDate?: string
  image: string
}

export type SideQuest = {
  id: string
  title: string
  description: string
  icon: 'camera' | 'food' | 'fox' | 'place' | 'quest' | 'route' | 'sparkles'
}

const cover = {
  osaka: '/assets/osaka-cover.webp',
  kyoto: '/assets/kyoto-cover.webp',
  tokyo: '/assets/tokyo-cover.webp',
  intro: '/assets/chonchetrip-splash.webp',
}

const badge = (name: string) => `/assets/achivments/${name}.webp`

export const tripDays: TripDay[] = [
  {
    id: 'belgrade-dubai',
    date: '2026-09-29',
    dateLabel: '29 сентября',
    city: 'Belgrade → Dubai',
    eyebrow: 'Пролог · Дорога на Восток',
    title: 'Путь к Японии начался',
    subtitle: 'Belgrade, ночной Dubai и ожидание главного рейса',
    cover: cover.intro,
    mapFile: '2026-09-30-arrival-osaka.html',
    mapNote: 'Общая карта 29–30 сентября. Локальные точки начинаются после прилёта в KIX.',
    fact: 'DXB Terminal 3 разделён на несколько concourse, поэтому после Transit сначала важнее проверить gate и только потом планировать прогулку по магазинам.',
    riddle: {
      question: 'Из какого терминала DXB отправляется рейс в Osaka?',
      hint: 'Ответ есть в билете на второй перелёт и на экранах Transit.',
      options: ['Terminal 1', 'Terminal 2', 'Terminal 3', 'Al Maktoum'],
      answer: 2,
      explanation: 'Следующий рейс начинается в DXB Terminal 3 — после Transit первым делом нужно проверить gate.',
      location: 'Dubai DXB · Terminal 3, экраны Transit',
    },
    timeline: [
      {
        id: 'beg-departure',
        time: '13:55',
        title: 'Поднять первый самолёт истории',
        kind: 'route',
        details: ['Belgrade BEG Terminal 2 → Dubai. Документы под рукой, впереди ночная пересадка и ещё один большой перелёт.'],
      },
      {
        id: 'dubai-arrival',
        time: '21:25',
        title: 'Приземлиться между двумя мирами',
        kind: 'route',
        details: ['Dubai DXB Terminal 3 → пройти Transit и сразу проверить gate рейса в Kansai.'],
      },
      {
        id: 'dubai-concourse-b',
        time: 'Если по пути',
        title: 'Заглянуть в Bath & Body Works',
        kind: 'place',
        details: ['Если маршрут проходит через Concourse B — спокойно посмотреть свечи, кремы и ароматы.', 'Не делать отдельный большой крюк, если следующий gate находится далеко.'],
      },
      {
        id: 'dubai-reset',
        time: 'До посадки',
        title: 'Перевести дыхание перед Японией',
        kind: 'rest',
        details: ['Найти воду, зарядку и место рядом с gate. В 03:00 начинается перелёт к Osaka.'],
      },
    ],
  },
  {
    id: 'arrival-osaka',
    date: '2026-09-30',
    dateLabel: '30 сентября',
    city: 'Osaka',
    eyebrow: 'Глава 01 · Прибытие',
    title: 'Первый фонарь зажжён',
    subtitle: 'DXB, KIX, билет Kuroshio и неон Dotonbori',
    cover: cover.osaka,
    mapFile: '2026-09-30-arrival-osaka.html',
    mapRouteScenes: [['kix-arrival'], ['kuroshio-ticket', 'stamp-kix'], ['to-hotel-osaka'], ['osaka-checkin'], ['dotonbori'], ['dotonbori'], ['dotonbori'], ['shinsaibashi-night']],
    achievementId: 'welcome-to-japan',
    achievementTitle: 'Welcome to Japan',
    claimLabel: 'Я в Японии!',
    fact: 'Японские станционные штампы называются eki stamp. Они бесплатные и часто спрятаны рядом с кассами или выходами станции.',
    riddle: {
      question: 'Какую победную позу застыл делать бегущий человек Glico?',
      hint: 'Встань на Ebisubashi и посмотри на самую знаменитую вывеску через канал.',
      options: ['Поднял обе руки', 'Скрестил руки', 'Держит факел', 'Показывает сердечко'],
      answer: 0,
      explanation: 'Бегущий человек пересекает воображаемый финиш с обеими руками над головой.',
      location: 'Dotonbori · вывеска Glico у моста Ebisubashi',
    },
    timeline: [
      {
        id: 'kix-arrival',
        time: '17:15',
        title: 'Шагнуть в Японию',
        kind: 'route',
        details: ['KIX Terminal 1 → Immigration: паспорт и Visit Japan Web QR.', 'Затем Baggage → Customs → Arrivals.'],
      },
      {
        id: 'kuroshio-ticket',
        time: 'После Customs',
        title: 'Купить билет на завтра',
        kind: 'quest',
        details: ['Подняться на 2F и перейти к Kansai-airport Station → JR-WEST Ticket Office / Midori-no-madoguchi.', 'Попросить: “Kuroshio 1, Tennoji to Shirahama, October 1, 7:59 AM. Two adults, reserved seats together.”', 'Купить только туда, два Reserved Seats рядом; оплатить картой.'],
      },
      {
        id: 'stamp-kix',
        time: 'Первая находка',
        title: 'Поставить печать начала пути',
        kind: 'quest',
        details: ['На Kansai Airport Station найти 駅スタンプ / Eki Stamp — это станционная печать #1.', 'Самостоятельно поставить её в туристический блокнот, не в загранпаспорт, а затем отметить находку в Passport приложения. К храмовым goshuin она не относится.'],
      },
      {
        id: 'to-hotel-osaka',
        time: 'После билетов',
        title: 'Прокатиться на первом японском поезде',
        kind: 'route',
        details: ['Kansai Airport → Nankai Rapi:t до Tengachaya.', 'На Tengachaya войти в Osaka Metro по Suica → Sakaisuji Line → Nagahoribashi → выход по Suica.', 'Exit 7 → около трёх минут пешком до Grand Hostel LDK Osaka Shinsaibashi.'],
      },
      {
        id: 'osaka-checkin',
        time: '~20:00',
        title: 'Сбросить рюкзаки',
        kind: 'rest',
        details: ['Check-in в Grand Hostel LDK Osaka Shinsaibashi и небольшой отдых перед неоном.'],
      },
      {
        id: 'dotonbori',
        time: '~20:30',
        title: 'Пройти неоновое крещение',
        kind: 'place',
        details: ['Dotonbori → Ebisu Bridge → вывеска Glico.', 'Перекус: Takoyaki Wanaka. Если захочется полноценного ужина — Ajinoya Honten и okonomiyaki.'],
      },
      {
        id: 'shinsaibashi-night',
        time: 'После ужина',
        title: 'Закрыть первый японский вечер',
        kind: 'place',
        details: ['Пройти через Shinsaibashi-suji, заглянуть в konbini по пути и вернуться в отель примерно к 23:00.', 'Проверить прогноз на завтра и собрать всё к раннему выходу. Выйти в 06:50, билет Kuroshio уже куплен.'],
      },
    ],
  },
  {
    id: 'shirahama',
    date: '2026-10-01',
    dateLabel: '1 октября',
    city: 'Shirahama',
    eyebrow: 'Глава 02 · Океан',
    title: 'К белому берегу',
    subtitle: 'Тихий океан, скалы и игровой вечер в Osaka',
    cover: cover.osaka,
    mapFile: '2026-10-01-shirahama.html',
    mapRouteScenes: [['early-breakfast'], ['train-shirahama'], ['train-shirahama', 'stamp-shirahama'], ['beach'], ['seafood'], ['coast'], ['coast'], ['coast'], ['parco'], ['parco']],
    achievementId: 'touch-the-pacific',
    achievementTitle: 'Touch the Pacific',
    claimLabel: 'Я коснулась Тихого океана',
    fact: 'Название Shirarahama буквально отсылает к белому песчаному берегу — именно ради него сегодня путь уходит далеко на юг.',
    riddle: {
      question: 'На сколько метров лифт уносит вниз к пещере Sandanbeki?',
      hint: 'Число можно заметить у входа или внутри лифта.',
      options: ['12 метров', '24 метра', '36 метров', '50 метров'],
      answer: 2,
      explanation: 'Лифт спускается на 36 метров — к пещере, которую Тихий океан выточил под скалами.',
      location: 'Sandanbeki · вход в пещеру и лифт',
    },
    timeline: [
      { id: 'early-breakfast', time: '06:50', title: 'Собрать завтрак охотника за океаном', kind: 'food', details: ['Egg sando, onigiri и кофе — всё остальное сделает поезд.'] },
      { id: 'train-shirahama', time: '07:59', title: 'Сбежать из города к океану', kind: 'route', details: ['Kuroshio 1 отправляется из Tennoji и через два часа привозит к белому берегу.'] },
      { id: 'stamp-shirahama', time: 'По прибытии', title: 'Найти печать с запахом океана', kind: 'quest', details: ['На Shirahama Station найти Eki Stamp #2 и самостоятельно поставить его в туристический блокнот.', 'После этого отметить вторую находку в Passport приложения. Это обычный станционный штамп, не храмовый goshuin.'] },
      { id: 'beach', time: 'До обеда', title: 'Коснуться Тихого океана', kind: 'quest', details: ['Разуться, выйти на белый песок и проверить, действительно ли океан холодный.'] },
      { id: 'seafood', time: 'Когда проголодаешься', title: 'Попробовать Тихий океан на вкус', kind: 'food', details: ['Выбирай то, что выглядит самым свежим: kaisendon, sashimi или рыбу дня.'] },
      { id: 'coast', time: 'После обеда', title: 'Пройти по краю мира', kind: 'place', details: ['Senjojiki и Sandanbeki — ветер, утёсы и океан без конца.'] },
      { id: 'parco', time: 'Вечером', title: 'Вернуться в мир игр перед отдыхом', kind: 'place', details: ['После берега вернуться в Osaka, выбрать один главный магазин — Kojima Productions или TORCH TORCH — и добавить ramen по аппетиту.', 'После этого без новых точек вернуться в отель, зарядить телефоны и приготовить QR-билеты к завтрашнему USJ.'] },
    ],
  },
  {
    id: 'usj',
    date: '2026-10-02',
    dateLabel: '2 октября',
    city: 'Osaka',
    eyebrow: 'Глава 03 · Другой мир',
    title: 'Портал открыт',
    subtitle: 'USJ, Frieren и Halloween Horror Nights',
    cover: cover.osaka,
    mapFile: '2026-10-02-usj.html',
    mapRouteScenes: [['to-usj'], ['to-usj'], ['to-usj', 'usj-entry'], ['harry-potter'], ['express-missions'], ['frieren-lunch'], ['express-missions'], ['halloween'], ['jurassic'], ['usj-home']],
    achievementId: 'another-world',
    achievementTitle: 'Another World',
    claimLabel: 'Главная миссия USJ выполнена',
    fact: 'Время выхода зависит от официального открытия USJ: цель — оказаться у ворот за 45–60 минут.',
    riddle: {
      question: 'Сколько мётел нужно найти на вывеске Three Broomsticks?',
      hint: 'Не переводи название — найди саму вывеску в деревне волшебников.',
      options: ['Одну', 'Две', 'Три', 'Четыре'],
      answer: 2,
      explanation: 'На вывеске собрались три метлы — иначе заведению пришлось бы менять название.',
      location: 'USJ · Hogsmeade, таверна Three Broomsticks',
    },
    timeline: [
      { id: 'to-usj', time: 'До открытия', title: 'Добраться до портала раньше толпы', kind: 'route', details: ['К воротам USJ стоит прийти за час — другие миры не любят опоздавших.'] },
      { id: 'usj-entry', time: 'Первым делом', title: 'Активировать магию Frieren', kind: 'quest', details: ['Покажи QR и сразу забери в приложении Frieren Story Walk eTicket на двоих.'] },
      { id: 'harry-potter', time: 'Утром', title: 'Выпить сливочного пива в Hogsmeade', kind: 'place', details: ['Потом можно проверить, насколько запретное путешествие действительно Forbidden.'] },
      { id: 'express-missions', time: 'Весь день', title: 'Собрать четыре мира за один день', kind: 'quest', details: ['Зомби, Frieren, Chainsaw Man и один очень быстрый Hollywood Dream.'] },
      { id: 'frieren-lunch', time: '~12:30–14:00', title: 'Зайти в Restaurant of Memories', kind: 'food', details: ['Сделать паузу в тематическом ресторане Frieren и выбрать коллаборационное блюдо или десерт.', 'Перед заказом свериться со временем следующего слота Express Pass.'] },
      { id: 'halloween', time: 'После 18:00', title: 'Дождаться, пока парк станет страшным', kind: 'place', details: ['Street Zombies и Zombie de Dance начинаются только после темноты.'] },
      { id: 'jurassic', time: '20:00', title: 'Прокатиться среди динозавров во тьме', kind: 'quest', details: ['Кульминация паркового дня — Jurassic Park in the Dark. После неё портал уже можно закрывать.'] },
      { id: 'usj-home', time: 'После 20:30', title: 'Закрыть портал и вернуться домой', kind: 'route', details: ['Universal City → JR Yumesaki Line до Nishikujo → Osaka Loop Line до Taisho.', 'На Taisho пересесть в Osaka Metro Nagahori Tsurumi-ryokuchi Line и доехать до Nagahoribashi. Дальше — Grand Hostel, душ, зарядка телефонов и никаких новых миссий.'] },
    ],
  },
  {
    id: 'nara',
    date: '2026-10-03',
    dateLabel: '3 октября',
    city: 'Nara',
    eyebrow: 'Глава 04 · Посланники леса',
    title: 'Выбрана Нара',
    subtitle: 'Олени, Великий Будда и вечер с Pokémon',
    cover: cover.osaka,
    mapFile: '2026-10-03-nara.html',
    mapRouteScenes: [['to-nara'], ['to-nara'], ['nara-park'], ['todaiji'], ['kasuga'], ['nara-food'], ['nara-food'], ['nara-food'], ['pokemon-osaka'], ['shinsekai-night'], ['shinsekai-night']],
    achievementId: 'chosen-by-nara',
    achievementTitle: 'Chosen by Nara',
    claimLabel: 'Я покормила оленя',
    fact: 'Shika senbei — специальные рисовые крекеры для оленей. Держи их спокойно и не прячь за спиной.',
    riddle: {
      question: 'Какой части Великого Будды равен лаз в деревянной колонне?',
      hint: 'Ищи колонну с отверстием внизу внутри Daibutsuden.',
      options: ['Уху', 'Глазу', 'Ноздре', 'Ладони'],
      answer: 2,
      explanation: 'Говорят, отверстие совпадает по размеру с ноздрёй Великого Будды.',
      location: 'Tōdai-ji · зал Daibutsuden, колонна позади статуи',
    },
    timeline: [
      { id: 'to-nara', time: 'Рано утром', title: 'Уехать туда, где олени важнее машин', kind: 'route', details: ['Rapid Express довезёт до Kintetsu-Nara примерно к девяти.'] },
      { id: 'nara-park', time: 'Первая встреча', title: 'Заслужить поклон оленя', kind: 'quest', details: ['Купи shika senbei и приготовься мгновенно стать самой популярной в парке.'] },
      { id: 'todaiji', time: 'Утром', title: 'Поздороваться с Великим Буддой', kind: 'place', details: ['Пройди через огромные ворота Nandaimon к Daibutsuden.'] },
      { id: 'kasuga', time: 'До обеда', title: 'Сосчитать фонари и сбиться', kind: 'place', details: ['Каменные и бронзовые фонари Kasuga Taisha специально не хотят считаться.'] },
      { id: 'nara-food', time: 'После полудня', title: 'Поймать ещё тёплый mochi', kind: 'food', details: ['Чайный домик, Naramachi и свежий yomogi mochi у Nakatanidou.'] },
      { id: 'pokemon-osaka', time: '~18:00', title: 'Поужинать в мире Pokémon', kind: 'quest', details: ['Прийти по брони в Pokémon Café Osaka на 9F Daimaru Shinsaibashi и спокойно прожить эту тематическую остановку отдельно от остального вечера.'] },
      { id: 'shinsekai-night', time: '~19:30', title: 'Отпустить маршрут в вечернем Shinsekai', kind: 'rest', details: ['Погулять под огнями Tsutenkaku, посмотреть ретро-вывески и никуда специально не торопиться.', 'Если снова проголодаетесь — взять kushikatsu в Daruma. Если нет — просто продолжить прогулку и поехать домой, когда захочется.'] },
    ],
  },
  {
    id: 'kyoto-arrival',
    date: '2026-10-04',
    dateLabel: '4 октября',
    city: 'Kyoto',
    eyebrow: 'Глава 05 · Старая столица',
    title: 'По следам дракона',
    subtitle: 'Kiyomizu-dera, Gion и первая запись goshuin',
    cover: cover.kyoto,
    mapFile: '2026-10-04-kyoto-gion.html',
    mapRouteScenes: [['move-kyoto'], ['move-kyoto'], ['move-kyoto', 'stamp-gion'], ['tazuru-bags'], ['kiyomizu'], ['old-streets'], ['old-streets'], ['old-streets'], ['gion'], ['tazuru-checkin'], ['gion-evening'], ['gion-evening'], ['gion-evening'], ['kaiseki']],
    achievementId: 'the-old-capital',
    achievementTitle: 'The Old Capital',
    claimLabel: 'Первый знак Kyoto открыт',
    fact: 'Goshuin оформляет служитель в отдельной книжке goshuincho. Это храмовая коллекция: к Travel Passport и станционным Eki stamp она не относится.',
    riddle: {
      question: 'Сколько драконов кружат на огромном потолке Kennin-ji?',
      hint: 'Войди в Dharma Hall и не забудь посмотреть вверх.',
      options: ['Один', 'Два', 'Три', 'Четыре'],
      answer: 1,
      explanation: 'Это «Twin Dragons» — пара драконов на потолке зала.',
      location: 'Kennin-ji · Dharma Hall / Hattō',
    },
    timeline: [
      { id: 'move-kyoto', time: 'После завтрака', title: 'Сменить неон на старую столицу', kind: 'route', details: ['Keihan увезёт прямо к Gion-Shijo — там начинается новая глава.'] },
      { id: 'stamp-gion', time: 'На станции', title: 'Поставить печать Kyoto', kind: 'quest', details: ['На Gion-Shijo Station найти Eki Stamp #3 и самостоятельно поставить его в туристический блокнот.', 'Затем отметить третью находку в Passport приложения. Goshuincho для этого не используется.'] },
      { id: 'tazuru-bags', time: 'Перед прогулкой', title: 'Оставить чемоданы и стать налегке', kind: 'rest', details: ['Tazuru приютит вещи до check-in.'] },
      { id: 'kiyomizu', time: 'До обеда', title: 'Начать отдельную книгу goshuin', kind: 'quest', details: ['У Kiyomizu-dera купить goshuincho — специальную книжку только для записей из храмов и святилищ.', 'Показать её в окне goshuin: служитель сам добавит каллиграфию и красную печать. В туристический блокнот это не ставится и в счётчик Eki stamp не входит.'] },
      { id: 'old-streets', time: 'После храма', title: 'Потеряться в старых улочках', kind: 'place', details: ['Sannenzaka, Ninenzaka, пагода и столько matcha-сладостей, сколько захочется.'] },
      { id: 'gion', time: '~15:40–16:40', title: 'Найти драконов Gion', kind: 'place', details: ['Зайти в Kennin-ji и посмотреть на пару огромных драконов на потолке Dharma Hall. После храма вернуться к Tazuru — он находится рядом.'] },
      { id: 'tazuru-checkin', time: '~17:00', title: 'По-настоящему заселиться в Kyoto', kind: 'rest', details: ['Вернуться в Tazuru, пройти check-in, забрать оставленные утром чемоданы и отнести вещи в номер.', 'Взять ключ, проверить самое нужное и сделать короткую паузу перед вечерней прогулкой.'] },
      { id: 'gion-evening', time: 'После check-in', title: 'Выйти к вечерним фонарям Gion', kind: 'place', details: ['Пройти через Hanamikoji к Yasaka Shrine, а затем выйти к тихому каналу Gion Shirakawa.', 'Это уже спокойная прогулка без багажа; к ужину перейти в Pontocho.'] },
      { id: 'kaiseki', time: '~18:30', title: 'Устроить самый красивый ужин поездки', kind: 'food', details: ['Kaiseki — ужин из нескольких небольших сезонных подач.', 'После Pontocho неспешно пройти вдоль Kamo River и вернуться в Tazuru.'] },
    ],
  },
  {
    id: 'fushimi',
    date: '2026-10-05',
    dateLabel: '5 октября',
    city: 'Kyoto',
    eyebrow: 'Глава 06 · Тысяча врат',
    title: 'Дорога сквозь тории',
    subtitle: 'Fushimi Inari, Nishiki и замок Nijo',
    cover: cover.kyoto,
    mapFile: '2026-10-05-fushimi-inari.html',
    mapRouteScenes: [['to-fushimi'], ['to-fushimi'], ['to-fushimi', 'fushimi-main'], ['fushimi-main'], ['sanjusangendo'], ['nishiki'], ['nijo'], ['matcha-night'], ['matcha-night'], ['matcha-night'], ['kyoto-night-finale']],
    achievementId: 'a-thousand-gates',
    achievementTitle: 'A Thousand Gates',
    claimLabel: 'Миссия Senbon Torii завершена',
    fact: 'Senbon Torii переводится как «тысяча ворот тории» — это знаменитый коридор красных врат Fushimi Inari.',
    riddle: {
      question: 'Пение какой птицы напоминают полы дворца Ninomaru?',
      hint: 'Ответ прячется не в картине — прислушайся к полу под ногами.',
      options: ['Журавля', 'Соловья', 'Совы', 'Воробья'],
      answer: 1,
      explanation: 'Скрипучие коридоры называют «соловьиными полами» — uguisubari.',
      location: 'Nijo Castle · коридоры Ninomaru Palace',
    },
    timeline: [
      { id: 'to-fushimi', time: 'Пока город спит', title: 'Уехать к лисьей горе', kind: 'route', details: ['Ранний Keihan — лучший шанс увидеть Fushimi Inari почти без толпы.'] },
      { id: 'fushimi-main', time: 'Утром', title: 'Пройти сквозь тысячу красных врат', kind: 'quest', details: ['Поднимайся через Senbon Torii до Yotsutsuji, пока Kyoto раскрывается внизу.'] },
      { id: 'sanjusangendo', time: 'После спуска', title: 'Встретить тысячу и одну статую', kind: 'place', details: ['В длинном зале Sanjusangendo попробуй найти две одинаковые.'] },
      { id: 'nishiki', time: 'В обед', title: 'Собрать обед по кусочкам', kind: 'food', details: ['Один tamagoyaki, кусочек свежей рыбы, что-нибудь жареное и wagashi на счастье.'] },
      { id: 'nijo', time: 'После рынка', title: 'Проверить, поют ли полы замка', kind: 'place', details: ['Прогулка через Ninomaru Palace и сады Nijo.'] },
      { id: 'matcha-night', time: 'Под вечер', title: 'Перейти от matcha к вечернему ramen', kind: 'food', details: ['Начните с зелёного parfait в Nakamura Tokichi, затем пройдите через Teramachi или Shinkyogoku.', 'Если появится настоящий голод — добавьте dashi ramen в Menya Inoichi Hanare. Если нет, спокойно переходите к выбору финала вечера.'] },
      { id: 'kyoto-night-finale', time: 'Когда захочется', title: 'Выбрать, как закончится Kyoto', kind: 'rest', details: ['Если силы закончились — спокойно возвращайтесь в Tazuru: душ, чай и отдых уже будут правильным финалом большого дня.', 'Если хочется ещё немного Kyoto — сделайте короткий круг вдоль Kamo River или по тихим вечерним улицам, не добавляя новых обязательных точек. После этого — домой в Tazuru.'] },
    ],
  },
  {
    id: 'arashiyama',
    date: '2026-10-06',
    dateLabel: '6 октября',
    city: 'Kyoto',
    eyebrow: 'Глава 07 · После заката',
    title: 'Тихий Arashiyama',
    subtitle: 'Бамбуковая роща, каменные лица и свет кимоно',
    cover: cover.kyoto,
    mapFile: '2026-10-06-arashiyama.html',
    mapRouteScenes: [['to-arashiyama'], ['to-arashiyama'], ['to-arashiyama', 'bridge-bamboo'], ['bridge-bamboo'], ['tenryuji'], ['tenryuji'], ['tenryuji'], ['tofu-lunch'], ['otagi'], ['otagi'], ['kimono-forest'], ['obanzai']],
    achievementId: 'kyoto-after-dark',
    achievementTitle: 'Kyoto After Dark',
    claimLabel: 'Я увидела Kimono Forest в огнях',
    fact: 'В Otagi Nenbutsu-ji около 1200 каменных rakan, и у каждой статуи своё лицо и настроение.',
    riddle: {
      question: 'Что спрятано внутри прозрачных светящихся колонн Kimono Forest?',
      hint: 'Подойди к одной колонне близко и рассмотри узор.',
      options: ['Ткань для кимоно', 'Рисовая бумага', 'Цветное стекло', 'Засушенные цветы'],
      answer: 0,
      explanation: 'Внутри находится ткань с традиционными узорами Kyo-yuzen.',
      location: 'Randen Arashiyama Station · Kimono Forest',
    },
    timeline: [
      { id: 'to-arashiyama', time: 'На рассвете', title: 'Сбежать в горы', kind: 'route', details: ['Тихий поезд довезёт до Arashiyama раньше основной толпы.'] },
      { id: 'bridge-bamboo', time: 'Первым делом', title: 'Услышать, как шепчет бамбук', kind: 'place', details: ['Начни у моста Togetsukyo и войди в рощу, пока она ещё сонная.'] },
      { id: 'tenryuji', time: 'Утром', title: 'Собрать три самых спокойных вида', kind: 'place', details: ['Сад Tenryu-ji, чай Okochi Sanso и река Hozu сверху.'] },
      { id: 'tofu-lunch', time: 'В обед', title: 'Попробовать Kyoto на вкус', kind: 'food', details: ['Горячий yudofu — простой обед, который неожиданно запоминается.'] },
      { id: 'otagi', time: 'После обеда', title: 'Найти каменное лицо с твоим настроением', kind: 'quest', details: ['В Otagi живут 1200 rakan — один из них точно похож на тебя сегодня.'] },
      { id: 'kimono-forest', time: 'После заката', title: 'Дождаться, когда зажжётся лес кимоно', kind: 'quest', details: ['Световые колонны Kimono Forest — вечерняя магия Arashiyama перед возвращением в центр Kyoto.'] },
      { id: 'obanzai', time: 'Вечером', title: 'Поужинать и отпустить Kyoto до утра', kind: 'food', details: ['В Kawaramachi выбрать несколько сезонных obanzai и спокойно восстановить силы после Arashiyama.', 'После ужина можно сразу вернуться в Tazuru или сделать один короткий круг вдоль Kamo River. Новых обязательных точек на сегодня нет.'] },
    ],
  },
  {
    id: 'hello-tokyo',
    date: '2026-10-07',
    dateLabel: '7 октября',
    city: 'Tokyo',
    eyebrow: 'Глава 08 · Новый горизонт',
    title: 'Hello, Tokyo',
    subtitle: 'Shinkansen и первый аниме-кадр Tokyo',
    cover: cover.tokyo,
    mapFile: '2026-10-07-kyoto-to-tokyo.html',
    mapRouteScenes: [['kyoto-station'], ['kyoto-station'], ['matcha-ekiben'], ['shinkansen'], ['tokyo-checkin'], ['shiba'], ['shiba'], ['tower'], ['jangara']],
    achievementId: 'hello-tokyo',
    achievementTitle: 'Hello, Tokyo',
    claimLabel: 'Первый знак Tokyo открыт',
    fact: 'Ekiben — вокзальный бенто, придуманный именно для поездки. Сегодня он становится обедом в Shinkansen.',
    riddle: {
      question: 'Что крутится в руках у маленьких каменных Jizō рядом с Zojo-ji?',
      hint: 'Ищи ряды маленьких статуй сбоку от основного храмового пространства.',
      options: ['Зонтики', 'Вертушки', 'Фонарики', 'Колокольчики'],
      answer: 1,
      explanation: 'Рядом с Jizō вращаются цветные вертушки, оставленные семьями вместе с одеждой и игрушками.',
      location: 'Zojo-ji · сад со статуями Jizō',
    },
    timeline: [
      { id: 'kyoto-station', time: 'Утром', title: 'Попрощаться с Kyoto', kind: 'route', details: ['Последний короткий путь к Kyoto Station — и старая столица остаётся позади.'] },
      { id: 'matcha-ekiben', time: 'Перед поездом', title: 'Собрать идеальный набор в Shinkansen', kind: 'food', details: ['Matcha-десерт сейчас, красивый ekiben — с собой.'] },
      { id: 'shinkansen', time: 'Около 12:30', title: 'Промчаться через Японию', kind: 'route', details: ['Nozomi доставит из Kyoto в Shinagawa быстрее, чем закончится ощущение дороги.'] },
      { id: 'tokyo-checkin', time: 'После прибытия', title: 'Оставить вещи в новом доме', kind: 'rest', details: ['Небольшая пауза в Shiba перед первым вечером Tokyo.'] },
      { id: 'shiba', time: 'Ближе к закату', title: 'Войти в кадр Weathering With You', kind: 'quest', details: ['Пройди через Zojo-ji в Shiba Park и поймай Tokyo Tower между деревьями. Не копируй кадр идеально — найди своё небо над городом.'] },
      { id: 'tower', time: 'Когда зажгутся огни', title: 'Подняться ближе к небу', kind: 'quest', details: ['Поднимись на Main Deck и дождись первых огней. Отметь обе точки — парк и башню — чтобы закрыть аниме-миссию.'] },
      { id: 'jangara', time: 'После башни', title: 'Закрепить знакомство ramen', kind: 'food', details: ['Tonkotsu ramen и спокойная прогулка домой через Shiba Park.', 'После переезда из Kyoto и первого вечера Tokyo этого достаточно: дальше только отдых в новом доме.'] },
    ],
  },
  {
    id: 'shibuya-story',
    date: '2026-10-08',
    dateLabel: '8 октября',
    city: 'Tokyo',
    eyebrow: 'Глава 09 · Живая сказка',
    title: 'От леса к неону',
    subtitle: 'Meiji, две аниме-миссии и неоновый Shibuya',
    cover: cover.tokyo,
    mapFile: '2026-10-08-harajuku-shibuya.html',
    mapRouteScenes: [['meiji'], ['meiji'], ['meiji'], ['jujutsu-route'], ['harajuku'], ['harajuku'], ['suga-steps'], ['gyukatsu'], ['shibuya'], ['shibuya'], ['shibuya'], ['shibuya'], ['shibuya-sky'], ['shinjuku-night'], ['shinjuku-night'], ['shinjuku-night'], ['ramen-nagi']],
    achievementId: 'into-the-storybook',
    achievementTitle: 'Into the Storybook',
    claimLabel: 'Я прошла от леса до ночных огней',
    fact: 'Сегодня маршрут специально меняет настроение: тишина лесной дороги Meiji Jingu постепенно превращается в неон Kabukicho.',
    riddle: {
      question: 'Бочки с каким напитком стоят напротив японских sake barrels?',
      hint: 'Найди две стены бочек на лесной дороге к святилищу.',
      options: ['С зелёным чаем', 'С пивом', 'С французским вином', 'С минеральной водой'],
      answer: 2,
      explanation: 'Напротив sake стоят бочки французского вина — знак дружбы Японии и Франции.',
      location: 'Meiji Jingu · главная дорога к святилищу',
    },
    timeline: [
      { id: 'meiji', time: 'Утром', title: 'Начать день в лесу посреди мегаполиса', kind: 'place', details: ['Большие torii, тишина Meiji Jingu и первый спокойный вдох Tokyo.'] },
      { id: 'jujutsu-route', time: 'На выходе к городу', title: 'Открыть свою главу Jujutsu Kaisen', kind: 'quest', details: ['Заметь название Meiji-jingumae, а позже закрой миссию среди экранов и переходов Shibuya. Нужен не точный кадр, а ощущение знакомого города — и никакой остановки посреди людского потока.'] },
      { id: 'harajuku', time: 'После тишины', title: 'Выйти из леса прямо в Harajuku', kind: 'place', details: ['Takeshita, Omotesando и Cat Street — смена миров за одну прогулку.'] },
      { id: 'suga-steps', time: 'До Shibuya', title: 'Встретиться на ступенях из «Твоего имени»', kind: 'quest', details: ['Сделай короткий прыжок до Yotsuya-sanchome и найди внешнюю лестницу Suga Shrine с красными перилами. Это тихий жилой уголок: один спокойный кадр — и дальше в путь.'] },
      { id: 'gyukatsu', time: 'После возвращения в Shibuya', title: 'Дожарить свой обед на камне', kind: 'food', details: ['Хрустящий gyukatsu требует маленького участия — и это половина удовольствия.'] },
      { id: 'shibuya', time: 'После обеда', title: 'Перейти самый знаменитый перекрёсток', kind: 'place', details: ['Поздоровайся с Hachiko, а потом отправляйся собирать мерч в PARCO.'] },
      { id: 'shibuya-sky', time: 'Вход 16:20–16:40', title: 'Поймать Tokyo между днём и ночью', kind: 'quest', details: ['Поднимись на SHIBUYA SKY до заката и останься до первых огней.'] },
      { id: 'shinjuku-night', time: 'После заката', title: 'Пойти туда, где живёт Godzilla', kind: 'place', details: ['Yakitori, Kabukicho и огромная голова над ночным Shinjuku.'] },
      { id: 'ramen-nagi', time: 'Финал', title: 'Найти ramen в переулках Golden Gai', kind: 'food', details: ['Насыщенный niboshi-бульон — заслуженная точка очень длинного дня.', 'После ужина сесть на Oedo Line до Daimon и спокойно идти домой. Если очередь слишком большая, ближайший уютный ramen будет не менее правильным финалом.'] },
    ],
  },
  {
    id: 'fuji',
    date: '2026-10-09',
    dateLabel: '9 октября',
    city: 'Fuji',
    eyebrow: 'Глава 10 · Гора появляется',
    title: 'Fuji Found!',
    subtitle: 'Chureito, Lake Kawaguchi и вид с канатной дороги',
    cover: cover.intro,
    mapFile: '2026-10-09-fuji.html',
    mapRouteScenes: [['fuji-train'], ['fuji-train'], ['fuji-train'], ['fuji-train'], ['chureito'], ['chureito'], ['houtou'], ['houtou'], ['oishi'], ['ropeway'], ['ropeway'], ['fuji-return']],
    achievementId: 'fuji-found',
    achievementTitle: 'Fuji Found!',
    claimLabel: 'Я увидела Fuji',
    fact: 'Этот контент можно целиком перенести на 11 октября, если видимость Fuji будет плохой. Награда переедет вместе с ним.',
    riddle: {
      question: 'Сколько ступеней отделяют начало подъёма от вида у Chureito?',
      hint: 'Число можно найти на указателе — или честно досчитать ногами.',
      options: ['108', '333', '398', '500'],
      answer: 2,
      explanation: 'До площадки ведут 398 каменных ступеней. Теперь каждая точно заслужена.',
      location: 'Arakurayama Sengen Park · лестница к Chureito',
    },
    timeline: [
      { id: 'fuji-train', time: 'Очень рано', title: 'Уехать на охоту за горой', kind: 'route', details: ['Fuji Excursion 3 стартует из Shinjuku в 07:30 — дальше всё решают облака.'] },
      { id: 'chureito', time: 'Первое испытание', title: 'Подняться к виду с открытки', kind: 'quest', details: ['Ступени к Chureito Pagoda приводят к тому самому кадру с Fuji.'] },
      { id: 'houtou', time: 'После подъёма', title: 'Согреться лапшой из котла', kind: 'food', details: ['Толстая hōtō, овощи и miso-бульон возвращают силы мгновенно.'] },
      { id: 'oishi', time: 'После обеда', title: 'Встретиться с Fuji у воды', kind: 'place', details: ['В Oishi Park между тобой и горой остаётся только озеро.'] },
      { id: 'ropeway', time: 'Перед вечером', title: 'Подняться ещё выше', kind: 'place', details: ['Канатная дорога покажет сразу и Fuji, и Lake Kawaguchi.'] },
      { id: 'fuji-return', time: '17:41', title: 'Увезти гору с собой', kind: 'route', details: ['Сесть у окна Fuji Excursion 48 и пересматривать фотографии до Tokyo.', 'После прибытия в Shinjuku вернуться к Hamamatsucho и домой. Этот вечер специально остаётся без новых обязательных планов.'] },
    ],
  },
  {
    id: 'ginza-akihabara',
    date: '2026-10-10',
    dateLabel: '10 октября',
    city: 'Tokyo',
    eyebrow: 'Глава 11 · Электрический город',
    title: 'Tokyo Explorer',
    subtitle: 'Tsukiji, покупки в Ginza и аниме-маршрут по Akihabara',
    cover: cover.tokyo,
    mapFile: '2026-10-10-ginza-akihabara.html',
    mapNote: 'Повторный заход в JINS отмечен в карточке точки JINS; расписание сцен выше остаётся главным.',
    mapRouteScenes: [['tsukiji-breakfast'], ['tsukiji-breakfast'], ['ginza-walk', 'jins', 'jins-pickup'], ['apple-ginza'], ['uniqlo-sushi'], ['sushi-midori'], ['ginza-to-akihabara', 'stamp-akihabara'], ['kanda-myojin-anime'], ['steins-gate-line'], ['steins-gate-line'], ['akihabara'], ['akihabara'], ['akihabara'], ['akihabara'], ['akiba-night', 'akiba-lights'], ['akiba-home']],
    achievementId: 'tokyo-explorer',
    achievementTitle: 'Tokyo Explorer',
    claimLabel: 'Главные точки Tokyo открыты',
    fact: 'Новые вещи можно брать сразу, а цены на редкий и used-мерч лучше запомнить или сфотографировать и завтра сравнить с Nakano Broadway.',
    riddle: {
      question: 'Какой цвет ведёт по указателям к поездам JR Yamanote?',
      hint: 'Не угадывай по памяти — найди полосу на платформе или схеме.',
      options: ['Красным', 'Салатовым', 'Фиолетовым', 'Чёрным'],
      answer: 1,
      explanation: 'Yamanote отмечена светло-зелёным цветом uguisu.',
      location: 'JR Akihabara · указатели или платформа Yamanote Line',
    },
    timeline: [
      { id: 'tsukiji-breakfast', time: '07:40–09:30', title: 'Начать день настоящим японским завтраком', kind: 'food', details: ['Выйти из жилья в 07:40, дойти до Daimon и по Suica проехать по Toei Asakusa Line до Higashi-ginza. От станции — около 10 минут пешком.', 'В Tsumugi at Tsukiji Honganji взять tamagoyaki, рис, miso soup, рыбу или гарниры и чай.'] },
      { id: 'ginza-walk', time: '09:45', title: 'Перейти из старого Tsukiji в блестящую Ginza', kind: 'route', details: ['До Ginza около 15 минут пешком — без пересадок и с утренними улицами Tokyo по пути.'] },
      { id: 'jins', time: '10:00–10:45', title: 'Выбрать новый взгляд на Tokyo', kind: 'quest', details: ['В JINS Ginza выбрать оправы обоим, пройти проверку зрения и заказать линзы.', 'Если стандартные линзы есть в наличии — получить время готовности в тот же день.'] },
      { id: 'apple-ginza', time: '10:50–11:20', title: 'Заглянуть во флагман Apple Ginza', kind: 'place', details: ['Коротко посмотреть четырёхэтажный магазин и не превращать остановку в отдельную экспедицию.'] },
      { id: 'uniqlo-sushi', time: '11:30–12:20', title: 'Подняться по двенадцати этажам UNIQLO Ginza', kind: 'place', details: ['Посмотреть одежду, коллаборации и японские коллекции в главном магазине UNIQLO.'] },
      { id: 'jins-pickup', time: '12:20–12:30', title: 'Проверить готовность очков', kind: 'quest', details: ['Если очки готовы — забрать. Если нет, оставить получение на потом или на 11 октября.'] },
      { id: 'sushi-midori', time: '12:45–13:45', title: 'Устроить суши-паузу в Ginza', kind: 'food', details: ['Обед в Sushi no Midori Ginza — заслуженная остановка перед электрическим городом.'] },
      { id: 'ginza-to-akihabara', time: 'После обеда', title: 'Переключиться на электрическую линию', kind: 'route', details: ['Дойти до Ginza Station, войти по Suica и по Hibiya Line доехать до Akihabara. После выхода перейти к станции JR.'] },
      { id: 'stamp-akihabara', time: 'Около 14:15', title: 'Поймать электрическую печать', kind: 'quest', details: ['В районе Central Gate станции JR найти 駅スタンプ / Eki Stamp #4.', 'Самостоятельно поставить его в туристический блокнот и отметить в Passport приложения. Книжка goshuincho здесь не нужна.'] },
      { id: 'kanda-myojin-anime', time: '14:30–15:00', title: 'Попросить удачу у хранителя Akihabara', kind: 'quest', details: ['От станции около 7–10 минут пешком до Kanda Myojin — святилища из мира Love Live! и Steins;Gate.', 'Для храмовой коллекции показать отдельную goshuincho служителю и попросить goshuin.', 'Ema — деревянная табличка для желания: можно выбрать иллюстрированную, написать желание и оставить на специальной стойке. Не фотографировать там, где это запрещено.'] },
      { id: 'steins-gate-line', time: 'С 15:10', title: 'Перейти на мировую линию Steins;Gate', kind: 'quest', details: ['Начать с Radio Kaikan у Electric Town Exit: культовая точка Steins;Gate, фигурки, мерч и AmiAmi.', 'Затем пройти через Manseibashi Bridge — ещё одну знакомую точку из аниме.'] },
      { id: 'akihabara', time: 'До 19:30', title: 'Начать большую охоту за сокровищами', kind: 'quest', details: ['Зайти в Mandarake Complex за used-мерчем, Super Potato за ретро-играми, animate Akihabara, GiGO и магазины Electric Town.', 'Новые вещи можно брать здесь; редкий и used-мерч сначала сравнить с завтрашним Nakano Broadway.'] },
      { id: 'akiba-night', time: 'Около 19:30', title: 'Выбрать ужин по цвету вывески', kind: 'food', details: ['Ramen, curry или izakaya в Akihabara — правильным будет то, что подходит по настроению и оставшимся силам.'] },
      { id: 'akiba-lights', time: '20:30–21:00', title: 'Запомнить Akihabara в неоне', kind: 'place', details: ['Последний круг по игровым центрам и магазинам, пока Electric Town светится ярче всего.'] },
      { id: 'akiba-home', time: 'После 21:00', title: 'Вернуться домой по зелёной линии', kind: 'route', details: ['От JR Akihabara по Suica сесть на Yamanote или Keihin-Tohoku Line до Hamamatsucho, выйти по Suica и дойти до жилья.', 'Перед сном проверить переключатель Fuji в Passport: если поездка состоялась 9 октября, завтра Asakusa, Ueno, Hama-rikyu, Murakami Library и Nakano; если перенесена — план Fuji.'] },
    ],
  },
  {
    id: 'asakusa-nakano',
    date: '2026-10-11',
    dateLabel: '11 октября',
    city: 'Tokyo',
    eyebrow: 'Глава 12 · Между книгой и неоном',
    title: 'Tokyo между строк',
    subtitle: 'Asakusa, сад на воде, Мураками и Nakano',
    cover: cover.tokyo,
    mapFile: '2026-10-11-asakusa-ueno-murakami.html',
    mapRouteScenes: [['konbini-asakusa'], ['sensoji'], ['nakamise-bite'], ['sumida'], ['ueno'], ['ameyoko'], ['hamarikyu'], ['hamarikyu'], ['murakami-library'], ['nakano'], ['nakano-dinner']],
    achievementId: 'lost-in-tokyo',
    achievementTitle: 'Lost in Tokyo',
    claimLabel: 'Я прошла Tokyo между строк',
    fact: 'Если план Fuji перенесён на сегодня, эта глава переедет на 9 октября вместе с наградой — переключатель ждёт в Passport.',
    riddle: {
      question: 'Что спрятано на нижней стороне огромного фонаря Kaminarimon?',
      hint: 'Встань под фонарём и посмотри вверх, а не на толпу.',
      options: ['Резной дракон', 'Золотая лиса', 'Карта Edo', 'Маленький колокол'],
      answer: 0,
      explanation: 'Снизу фонаря скрывается резной дракон — маленькая награда для тех, кто смотрит не только вперёд.',
      location: 'Asakusa · ворота Kaminarimon',
    },
    timeline: [
      { id: 'konbini-asakusa', time: '07:05', title: 'Собрать завтрак путешественницы', kind: 'food', details: ['Egg sando, onigiri и кофе из 7-Eleven — съесть без спешки по дороге к Daimon. Дальше одна линия ведёт прямо в Asakusa.'] },
      { id: 'sensoji', time: '08:00–09:45', title: 'Разбудить старый Tokyo', kind: 'quest', details: ['Пройди под Kaminarimon, загляни на Nakamise и доберись до Senso-ji, пока храм ещё не растворился в толпе.', 'Если хочется продолжить храмовую коллекцию, показать отдельную goshuincho в окне goshuin — служитель добавит новую запись. Это не Eki stamp и не отметка в Passport приложения.', 'Вход на территорию свободный.'] },
      { id: 'nakamise-bite', time: 'По пути', title: 'Выбрать сладость у старой улицы', kind: 'food', details: ['Ningyo-yaki или тёплый melon pan — сегодня решение принимает запах.'] },
      { id: 'sumida', time: '09:45–10:20', title: 'Поймать Skytree в реке', kind: 'place', details: ['Пройдись по набережной Sumida и найди отражение башни между лодками и мостами. Потом короткий переезд по Ginza Line до Ueno.'] },
      { id: 'ueno', time: '10:40–11:30', title: 'Спрятаться у пруда Shinobazu', kind: 'place', details: ['Ueno Park даст тихую передышку: вода, лотосы и один круг без обязательных достопримечательностей.'] },
      { id: 'ameyoko', time: '11:30–12:30', title: 'Позволить рынку выбрать обед', kind: 'food', details: ['На Ameyoko побеждает то, что вкуснее пахнет прямо сейчас: donburi, seafood, yakitori или случайная уличная находка.'] },
      { id: 'hamarikyu', time: '13:15–14:40', title: 'Найти сад, который дышит вместе с заливом', kind: 'place', details: ['От Shimbashi — около 12 минут пешком до Hama-rikyu. Приливный пруд меняется вместе с Tokyo Bay, а вокруг него отражаются небоскрёбы.', 'Вход ¥300. На островке Nakajima-no-ochaya можно остановиться ради matcha и wagashi.'] },
      { id: 'murakami-library', time: '15:25–16:40', title: 'Войти в роман Мураками', kind: 'quest', details: ['В Waseda International House of Literature найди настоящий рояль из джаз-бара Peter Cat — тот самый инструмент, рядом с которым музыка стала частью будущих книг.', 'Дальше собери личный маршрут: кабинет писателя, переводы со всего мира, коллекция пластинок, Sheep Man и сценический Saturn из «Кафки на пляже».', 'Вход свободный, бронь для обычного визита не нужна. Orange Cat считай бонусом: у кафе отдельный график и по воскресеньям оно обычно закрыто.'] },
      { id: 'nakano', time: '17:10–20:00', title: 'Открыть финальный уровень охоты', kind: 'quest', details: ['Tozai Line довезёт от Waseda прямо до Nakano. Пройди через Sun Mall в Nakano Broadway и сравни находки Mandarake с ценами Akihabara.', 'Редкий used merch, фигурки, манга и старые игры — покупать только то, что вызывает настоящее «нашла!».'] },
      { id: 'nakano-dinner', time: 'После 20:00', title: 'Отпраздновать находки без сценария', kind: 'food', details: ['Ramen, yakitori или маленькая izakaya в Nakano — выбирай по настроению и количеству оставшихся сил.', 'Домой: Chuo Line до Shinjuku, затем Oedo Line до Daimon. Завтрашний checkout уже подождёт.'] },
    ],
  },
  {
    id: 'last-day',
    date: '2026-10-12',
    dateLabel: '12 октября',
    city: 'Tokyo',
    eyebrow: 'Глава 13 · Последний фонарь',
    title: 'Ещё один вечер',
    subtitle: 'Tokyo Station, Odaiba и дорога к Haneda',
    cover: cover.tokyo,
    mapFile: '2026-10-12-last-day.html',
    mapRouteScenes: [['checkout-locker'], ['checkout-locker'], ['marunouchi'], ['marunouchi'], ['marunouchi'], ['rokurinsha'], ['rokurinsha'], ['odaiba'], ['odaiba'], ['odaiba'], ['odaiba'], ['bags-haneda'], ['bags-haneda', 'haneda']],
    achievementId: 'one-more-night',
    achievementTitle: 'One More Night',
    claimLabel: 'Последний вечер сохранён',
    fact: 'Чемоданы остаются в coin locker на Hamamatsucho — так последний день можно пройти налегке.',
    riddle: {
      question: 'Сколько животных японского зодиака спрятано под куполом Tokyo Station?',
      hint: 'Зайди со стороны Marunouchi и медленно обведи глазами весь купол.',
      options: ['Четыре', 'Шесть', 'Восемь', 'Двенадцать'],
      answer: 2,
      explanation: 'В восьми углах купола спрятаны восемь из двенадцати животных зодиака.',
      location: 'Tokyo Station · северный или южный купол Marunouchi',
    },
    timeline: [
      { id: 'checkout-locker', time: 'Утром', title: 'Спрятать чемоданы и украсть ещё один день', kind: 'route', details: ['Coin locker на Hamamatsucho освободит руки до самого вечера.'] },
      { id: 'marunouchi', time: 'До обеда', title: 'Увидеть Tokyo из старой открытки', kind: 'place', details: ['Красный вокзал, Marunouchi и каменный мост Nijubashi.'] },
      { id: 'rokurinsha', time: 'В обед', title: 'Научиться правильно есть tsukemen', kind: 'food', details: ['Лапша отдельно, густой бульон отдельно — встречаются они только перед укусом.'] },
      { id: 'odaiba', time: 'Последний длинный вечер', title: 'Уехать на остров будущего', kind: 'place', details: ['Tokyo Bay, Rainbow Bridge, маленькая Liberty и последние спонтанные покупки.'] },
      { id: 'bags-haneda', time: 'После 19:00', title: 'Забрать чемоданы и ехать за последним билетом', kind: 'route', details: ['Monorail от Hamamatsucho довезёт прямо к Haneda Terminal 3.'] },
      { id: 'haneda', time: 'Около 20:30', title: 'Зажечь последний фонарь', kind: 'quest', details: ['Всё формальное позади — дальше только gate, тишина и воспоминания.'] },
    ],
  },
  {
    id: 'finale',
    date: '2026-10-13',
    dateLabel: '13 октября',
    city: 'Finale',
    eyebrow: 'Финал · Путь продолжается',
    title: 'Japan Complete',
    subtitle: 'Последняя страница — и первая память о путешествии',
    cover: cover.intro,
    mapFile: '2026-10-12-last-day.html',
    mapNote: 'Общая карта 12–13 октября: ночной рейс начинается в точке Haneda Terminal 3.',
    mapRouteScenes: [['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight'], ['flight']],
    mapStartProgress: 13,
    achievementId: 'japan-complete',
    achievementTitle: 'Japan Complete',
    claimLabel: 'Завершить историю',
    fact: 'Финальная глава ничего не проверяет. Она просто собирает маршрут, фотографии и найденные награды в одну историю.',
    riddle: {
      question: 'Как называется японский подарок, который привозят из путешествия?',
      hint: 'Обычно это красиво упакованная местная вкусность для близких.',
      options: ['Omiyage', 'Omikuji', 'Goshuin', 'Yukata'],
      answer: 0,
      explanation: 'Omiyage — маленький подарок из поездки. И да, воспоминания тоже считаются.',
    },
    timeline: [
      { id: 'flight', time: '00:05', title: 'Унести Японию с собой', kind: 'route', details: ['Самолёт улетает, но маленькая Япония уже спрятана внутри тебя.'] },
      { id: 'final-recap', time: 'Когда захочется', title: 'Открыть коробку воспоминаний', kind: 'quest', details: ['Перелистай бейджи и фотографии, а потом выбери главу, которую хочется прожить ещё раз.'] },
    ],
  },
]

export const sideQuests: SideQuest[] = [
  {
    id: 'manhole-hunter',
    title: 'Охотница за люками',
    description: 'Найти и сфотографировать самый красивый японский люк.',
    icon: 'camera',
  },
  {
    id: 'vending-roulette',
    title: 'Вендинг-рулетка',
    description: 'Выбрать незнакомый напиток только по дизайну банки.',
    icon: 'sparkles',
  },
  {
    id: 'gachapon-oracle',
    title: 'Оракул gachapon',
    description: 'Один раз доверить выбор капсулы чистой случайности.',
    icon: 'quest',
  },
  {
    id: 'paper-fortune',
    title: 'Бумажная судьба',
    description: 'Вытянуть omikuji и узнать, что приготовила удача.',
    icon: 'fox',
  },
  {
    id: 'mascot-encounter',
    title: 'Встреча с талисманом',
    description: 'Найти местного mascot: живого, на вывеске или упаковке.',
    icon: 'camera',
  },
  {
    id: 'plastic-masterpiece',
    title: 'Пластиковый шедевр',
    description: 'Отыскать витрину с едой, которая выглядит вкуснее настоящей.',
    icon: 'food',
  },
  {
    id: 'tiny-shrine',
    title: 'Тайное святилище',
    description: 'Заметить крошечный храм или torii среди большого города.',
    icon: 'place',
  },
  {
    id: 'station-melody',
    title: 'Мелодия пути',
    description: 'Услышать станционную мелодию и выбрать любимую за поездку.',
    icon: 'route',
  },
  {
    id: 'anime-frame',
    title: 'Оживший кадр',
    description: 'Снять свою версию любого аниме-кадра, не перекрывая дорогу прохожим.',
    icon: 'camera',
  },
]

export const achievements: Achievement[] = [
  { id: 'welcome-to-japan', title: 'Welcome to Japan', description: 'Первый шаг после прилёта в Osaka.', type: 'story', unlockDate: '2026-09-30', image: badge('welcome-to-japan') },
  { id: 'touch-the-pacific', title: 'Touch the Pacific', description: 'Белый берег Shirahama и Тихий океан.', type: 'story', unlockDate: '2026-10-01', image: badge('touch-the-pacific') },
  { id: 'another-world', title: 'Another World', description: 'Главная миссия в другом мире USJ.', type: 'story', unlockDate: '2026-10-02', image: badge('another-world') },
  { id: 'chosen-by-nara', title: 'Chosen by Nara', description: 'Встреча с оленями Nara.', type: 'story', unlockDate: '2026-10-03', image: badge('chosen-by-nara') },
  { id: 'the-old-capital', title: 'The Old Capital', description: 'Первый знак старой столицы.', type: 'story', unlockDate: '2026-10-04', image: badge('the-old-capital') },
  { id: 'a-thousand-gates', title: 'A Thousand Gates', description: 'Путь через Senbon Torii.', type: 'story', unlockDate: '2026-10-05', image: badge('a-thousand-gates') },
  { id: 'kyoto-after-dark', title: 'Kyoto After Dark', description: 'Свет Kimono Forest после заката.', type: 'story', unlockDate: '2026-10-06', image: badge('kyoto-after-dark') },
  { id: 'hello-tokyo', title: 'Hello, Tokyo', description: 'Первый вечер под Tokyo Tower.', type: 'story', unlockDate: '2026-10-07', image: badge('hello-tokyo') },
  { id: 'into-the-storybook', title: 'Into the Storybook', description: 'От леса Meiji до огней Shinjuku.', type: 'story', unlockDate: '2026-10-08', image: badge('into-the-storybook') },
  { id: 'fuji-found', title: 'Fuji Found!', description: 'Fuji показалась из-за облаков.', type: 'story', unlockDate: '2026-10-09', image: badge('fuji-found') },
  { id: 'tokyo-explorer', title: 'Tokyo Explorer', description: 'Главные точки большого города открыты.', type: 'story', unlockDate: '2026-10-10', image: badge('tokyo-explorer') },
  { id: 'lost-in-tokyo', title: 'Lost in Tokyo', description: 'Путь от фонаря Asakusa через мир Мураками до Nakano.', type: 'story', unlockDate: '2026-10-11', image: badge('lost-in-tokyo') },
  { id: 'one-more-night', title: 'One More Night', description: 'Последний вечер путешествия сохранён.', type: 'story', unlockDate: '2026-10-12', image: badge('one-more-night') },
  { id: 'japan-complete', title: 'Japan Complete', description: 'Финальный recap завершён.', type: 'story', unlockDate: '2026-10-13', image: badge('japan-complete') },
  { id: 'weather-child', title: 'Weather Child', description: 'Собран свой кадр между Shiba Park и Tokyo Tower.', type: 'secret', image: badge('weather-child') },
  { id: 'shibuya-incident', title: 'Shibuya Incident', description: 'Маршрут Meiji-jingumae — Shibuya пройден по следам Jujutsu Kaisen.', type: 'secret', image: badge('shibuya-incident') },
  { id: 'i-remember-you', title: 'I Remember You', description: 'Ступени Suga Shrine из «Твоего имени» найдены.', type: 'secret', image: badge('i-remember-you') },
  { id: 'el-psy-kongroo', title: 'El Psy Kongroo', description: 'Kanda Myojin, Radio Kaikan и Manseibashi соединились в одной мировой линии.', type: 'secret', image: badge('el-psy-kongroo') },
  { id: 'ramen-initiation', title: 'Ramen Initiation', description: 'Первый ramen поездки.', type: 'secret', image: badge('ramen-initiation') },
  { id: 'konbini-connoisseur', title: 'Konbini Connoisseur', description: 'Находки из трёх разных konbini.', type: 'secret', image: badge('konbini-connoisseur') },
  { id: 'stamp-hunter', title: 'Stamp Hunter', description: 'Пять японских туристических штампов.', type: 'secret', image: badge('stamp-hunter') },
  { id: 'night-owl', title: 'Night Owl', description: 'Вечерние главы Osaka, Kyoto и Tokyo.', type: 'meta', image: badge('night-owl') },
  { id: 'three-cities', title: 'Three Cities, One Journey', description: 'Osaka, Kyoto и Tokyo открыты.', type: 'meta', image: badge('three-cities-one-journey') },
  { id: 'perfect-day', title: 'Perfect Day', description: 'Один из дней получил 10/10.', type: 'secret', image: badge('perfect-day') },
  { id: 'memory-keeper', title: 'Memory Keeper', description: 'Сохранено пять Photo of the Day.', type: 'secret', image: badge('memory-keeper') },
  { id: 'no-spoilers', title: 'No Spoilers', description: 'Путь до Tokyo пройден без спойлеров из будущих глав.', type: 'secret', image: badge('no-spoilers') },
  { id: 'curious-fox', title: 'Curious Fox', description: 'Пять подсказок Кицу использованы по дороге.', type: 'secret', image: badge('curious-fox') },
  { id: 'field-researcher', title: 'Field Researcher', description: 'Первая полевая загадка успешно решена.', type: 'secret', image: badge('field-researcher') },
  { id: 'keen-eye', title: 'Keen Eye', description: 'Пять настоящих улик замечены по дороге.', type: 'secret', image: badge('keen-eye') },
  { id: 'kitsus-equal', title: "Kitsu's Equal", description: 'Все полевые загадки путешествия разгаданы.', type: 'meta', image: badge('kitsus-equal') },
  { id: 'foxfire-constellation', title: 'Foxfire Constellation', description: 'Все 15 лисьих огней сложились в созвездие Кицу.', type: 'meta', image: badge('foxfire-constellation') },
  { id: 'side-quest-accepted', title: 'Side Quest Accepted', description: 'Первая случайная миссия выбрана и выполнена.', type: 'secret', image: badge('side-quest-accepted') },
  { id: 'manhole-hunter', title: 'Manhole Hunter', description: 'Найден самый красивый японский люк.', type: 'secret', image: badge('manhole-hunter') },
  { id: 'capsule-of-fate', title: 'Capsule of Fate', description: 'Судьба доверена одному gachapon.', type: 'secret', image: badge('capsule-of-fate') },
  { id: 'fortune-found', title: 'Fortune Found', description: 'Бумажное предсказание omikuji найдено.', type: 'secret', image: badge('fortune-found') },
  { id: 'wandering-legend', title: 'Wandering Legend', description: 'Выполнены все миссии без маршрута.', type: 'meta', image: badge('wandering-legend') },
  { id: 'japan-collector', title: 'Japan Collector', description: 'Собрано 15 любых достижений.', type: 'meta', image: badge('japan-collector') },
  { id: 'completionist', title: 'Completionist', description: 'Собраны все доступные достижения.', type: 'meta', image: badge('completionist') },
]

export const passportStamps = [
  { id: 'kix', title: 'Kansai Airport', subtitle: 'Kansai Airport Station' },
  { id: 'shirahama', title: 'Shirahama', subtitle: 'Shirahama Station' },
  { id: 'gion', title: 'Gion-Shijo', subtitle: 'Gion-Shijo Station' },
  { id: 'akihabara', title: 'Akihabara', subtitle: 'JR · Central Gate' },
  { id: 'wildcard', title: 'Секретный штамп', subtitle: 'Любой обычный туристический штамп' },
]
